from enum import Enum


class UploadState(str, Enum):
    DISCONNECTED = "DISCONNECTED"
    SCANNING = "SCANNING"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    GATT_VALIDATED = "GATT_VALIDATED"
    NOTIFY_ENABLED = "NOTIFY_ENABLED"
    LISTENING = "LISTENING"
    DISCONNECTING = "DISCONNECTING"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

