from enum import Enum


class UploadState(str, Enum):
    DISCONNECTED = "DISCONNECTED"
    SCANNING = "SCANNING"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    GATT_VALIDATED = "GATT_VALIDATED"
    NOTIFY_ENABLED = "NOTIFY_ENABLED"
    LISTENING = "LISTENING"
    C8_SENT = "C8_SENT"
    COUNTDOWN = "COUNTDOWN"
    D1_READY = "D1_READY"
    C8_CONFIRMED = "C8_CONFIRMED"
    PREPARE_VERIFIED = "PREPARE_VERIFIED"
    SENDING_C9 = "SENDING_C9"
    WAITING_CA_SUCCESS = "WAITING_CA_SUCCESS"
    CA_SUCCESS_RECEIVED = "CA_SUCCESS_RECEIVED"
    CA_APPLY_SENT = "CA_APPLY_SENT"
    DISCONNECTING = "DISCONNECTING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
